// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer.EntityFramework.Context;

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(FootballManagerContext))]
    [Migration("20180610120246_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainModels.Models.BuildingEntities.Building", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ClubId")
                        .HasColumnName("CLUB_ID");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("Level")
                        .HasColumnName("LEVEL");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("BUILDINGS");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Building");
                });

            modelBuilder.Entity("DomainModels.Models.Club", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Country")
                        .HasColumnName("COUNTRY");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnName("FOUNDATION_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasMaxLength(64);

                    b.Property<long>("UserId")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CLUBS");
                });

            modelBuilder.Entity("DomainModels.Models.EmployeeEntities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ClubId")
                        .HasColumnName("CLUB_ID");

                    b.Property<int>("Country")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FIRST_NAME")
                        .HasMaxLength(64);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LAST_NAME")
                        .HasMaxLength(64);

                    b.Property<int>("Level")
                        .HasColumnName("LEVEL");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("EMPLOYEES");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Employee");
                });

            modelBuilder.Entity("DomainModels.Models.PlayerEntities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnName("AGE");

                    b.Property<int>("BodyType")
                        .HasColumnName("BODY_TYPE");

                    b.Property<long>("ClubId")
                        .HasColumnName("CLUB_ID");

                    b.Property<int>("Country")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FIRST_NAME")
                        .HasMaxLength(64);

                    b.Property<int>("Height")
                        .HasColumnName("HEIGHT");

                    b.Property<int>("HeightType")
                        .HasColumnName("HEIGHT_TYPE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LAST_NAME")
                        .HasMaxLength(64);

                    b.Property<int>("Position")
                        .HasColumnName("POSITION");

                    b.Property<int>("Talent")
                        .HasColumnName("TALENT");

                    b.Property<int>("Weight")
                        .HasColumnName("WEIGHT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("PLAYERS");
                });

            modelBuilder.Entity("DomainModels.Models.PlayerEntities.PlayerStats", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("ID");

                    b.Property<float>("Acceleration")
                        .HasColumnName("ACCELERATION");

                    b.Property<float>("Agility")
                        .HasColumnName("AGILITY");

                    b.Property<float>("BallControl")
                        .HasColumnName("BALL_CONTROL");

                    b.Property<float>("Crossing")
                        .HasColumnName("CROSSING");

                    b.Property<float>("FreeKicks")
                        .HasColumnName("FREE_KICKS");

                    b.Property<float>("HandPlay")
                        .HasColumnName("HAND_PLAY");

                    b.Property<float>("Heading")
                        .HasColumnName("HEADING");

                    b.Property<float>("Interceptions")
                        .HasColumnName("INTERCEPTIONS");

                    b.Property<float>("Jumping")
                        .HasColumnName("JUMPING");

                    b.Property<float>("Kicking")
                        .HasColumnName("KICKING");

                    b.Property<float>("LongPassing")
                        .HasColumnName("LONG_PASSING");

                    b.Property<float>("LongShots")
                        .HasColumnName("LONG_SHOTS");

                    b.Property<float>("Penalties")
                        .HasColumnName("PENALTIES");

                    b.Property<float>("Positioning")
                        .HasColumnName("POSITIONING");

                    b.Property<float>("Reflexes")
                        .HasColumnName("REFLEXES");

                    b.Property<float>("ShortPassing")
                        .HasColumnName("SHORT_PASSING");

                    b.Property<float>("Shots")
                        .HasColumnName("SHOTS");

                    b.Property<float>("SlidingTackles")
                        .HasColumnName("SLIDING_TACKLES");

                    b.Property<float>("SprintSpeed")
                        .HasColumnName("SPRINT_SPEED");

                    b.Property<float>("Stamina")
                        .HasColumnName("STAMINA");

                    b.Property<float>("StandingTackles")
                        .HasColumnName("STANDING_TACKLES");

                    b.Property<float>("Strength")
                        .HasColumnName("STRENGTH");

                    b.Property<float>("Tricks")
                        .HasColumnName("TRICKS");

                    b.HasKey("Id");

                    b.ToTable("PLAYER_STATS");
                });

            modelBuilder.Entity("DomainModels.Models.PlayerEntities.PlayerTemporaryStats", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("ID");

                    b.Property<int>("Injury")
                        .HasColumnName("INJURY");

                    b.Property<DateTime>("InjuryDateTime")
                        .HasColumnName("INJURY_DATE_TIME");

                    b.Property<int>("Morale")
                        .HasColumnName("MORALE");

                    b.Property<DateTime>("MoraleDateTime")
                        .HasColumnName("MORALE_DATE_TIME");

                    b.Property<int>("Stamina")
                        .HasColumnName("STAMINA");

                    b.Property<DateTime>("StaminaDateTime")
                        .HasColumnName("STAMINA_DATE_TIME");

                    b.HasKey("Id");

                    b.ToTable("PLAYER_TEMPORARY_STATS");
                });

            modelBuilder.Entity("DomainModels.Models.SquadEntities.FormationPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FormationPositionType")
                        .HasColumnName("FORMATION_POSITION_TYPE");

                    b.Property<long?>("PlayerId")
                        .HasColumnName("PLAYER_ID");

                    b.Property<int>("PlayerPosition")
                        .HasColumnName("PLAYER_POSITION");

                    b.Property<long>("SquadId")
                        .HasColumnName("SQUAD_ID");

                    b.HasKey("Id");

                    b.HasIndex("SquadId");

                    b.ToTable("FORMATION_POSITIONS");
                });

            modelBuilder.Entity("DomainModels.Models.SquadEntities.Squad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ClubId")
                        .HasColumnName("CLUB_ID");

                    b.Property<int>("Formation")
                        .HasColumnName("FORMATION");

                    b.Property<bool>("IsActive")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("SQUADS");
                });

            modelBuilder.Entity("DomainModels.Models.TournamentEntities.Match", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("HomeId")
                        .HasColumnName("HOME_ID");

                    b.Property<long>("TournamentId")
                        .HasColumnName("TOURNAMENT_ID");

                    b.Property<long>("VisitorsId")
                        .HasColumnName("VISITORS_ID");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("MATCHES");
                });

            modelBuilder.Entity("DomainModels.Models.TournamentEntities.MatchEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MatchEventType")
                        .HasColumnName("FORMATION");

                    b.Property<long>("MatchId")
                        .HasColumnName("MATCH_ID");

                    b.Property<long>("PlayerId")
                        .HasColumnName("PLAYER_ID");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MATCH_EVENTS");
                });

            modelBuilder.Entity("DomainModels.Models.TournamentEntities.Tournament", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentStage")
                        .HasColumnName("CURRENT_STAGE");

                    b.Property<int>("Level")
                        .HasColumnName("LEVEL");

                    b.Property<int>("TournamentType")
                        .HasColumnName("TOURNAMENT_TYPE");

                    b.HasKey("Id");

                    b.ToTable("TOURNAMENTS");
                });

            modelBuilder.Entity("DomainModels.Models.TournamentEntities.TournamentClub", b =>
                {
                    b.Property<long>("TournamentId")
                        .HasColumnName("TOURNAMENT_ID");

                    b.Property<long>("ClubId")
                        .HasColumnName("CLUB_ID");

                    b.HasKey("TournamentId", "ClubId");

                    b.HasIndex("ClubId");

                    b.ToTable("TOURNAMENT_CLUBS");
                });

            modelBuilder.Entity("DomainModels.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Boosters")
                        .HasColumnName("BOOSTERS");

                    b.Property<int>("Coins")
                        .HasColumnName("COINS");

                    b.Property<int>("Country")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FIRST_NAME")
                        .HasMaxLength(64);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LAST_NAME")
                        .HasMaxLength(64);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("LOGIN")
                        .HasMaxLength(64);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("PASSWORD")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("DomainModels.Models.BuildingEntities.Academy", b =>
                {
                    b.HasBaseType("DomainModels.Models.BuildingEntities.Building");


                    b.ToTable("Academy");

                    b.HasDiscriminator().HasValue("Academy");
                });

            modelBuilder.Entity("DomainModels.Models.BuildingEntities.FanClub", b =>
                {
                    b.HasBaseType("DomainModels.Models.BuildingEntities.Building");

                    b.Property<int>("FansCount")
                        .HasColumnName("FANS_COUNT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasMaxLength(64);

                    b.ToTable("FanClub");

                    b.HasDiscriminator().HasValue("FanClub");
                });

            modelBuilder.Entity("DomainModels.Models.BuildingEntities.MedicalCenter", b =>
                {
                    b.HasBaseType("DomainModels.Models.BuildingEntities.Building");


                    b.ToTable("MedicalCenter");

                    b.HasDiscriminator().HasValue("MedicalCenter");
                });

            modelBuilder.Entity("DomainModels.Models.BuildingEntities.Stadium", b =>
                {
                    b.HasBaseType("DomainModels.Models.BuildingEntities.Building");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasMaxLength(64);

                    b.ToTable("Stadium");

                    b.HasDiscriminator().HasValue("Stadium");
                });

            modelBuilder.Entity("DomainModels.Models.BuildingEntities.TrainingCenter", b =>
                {
                    b.HasBaseType("DomainModels.Models.BuildingEntities.Building");


                    b.ToTable("TrainingCenter");

                    b.HasDiscriminator().HasValue("TrainingCenter");
                });

            modelBuilder.Entity("DomainModels.Models.EmployeeEntities.HeadCoach", b =>
                {
                    b.HasBaseType("DomainModels.Models.EmployeeEntities.Employee");


                    b.ToTable("HeadCoach");

                    b.HasDiscriminator().HasValue("HeadCoach");
                });

            modelBuilder.Entity("DomainModels.Models.EmployeeEntities.HeadCoachAssistent", b =>
                {
                    b.HasBaseType("DomainModels.Models.EmployeeEntities.Employee");


                    b.ToTable("HeadCoachAssistent");

                    b.HasDiscriminator().HasValue("HeadCoachAssistent");
                });

            modelBuilder.Entity("DomainModels.Models.EmployeeEntities.Medic", b =>
                {
                    b.HasBaseType("DomainModels.Models.EmployeeEntities.Employee");


                    b.ToTable("Medic");

                    b.HasDiscriminator().HasValue("Medic");
                });

            modelBuilder.Entity("DomainModels.Models.EmployeeEntities.Psychologist", b =>
                {
                    b.HasBaseType("DomainModels.Models.EmployeeEntities.Employee");


                    b.ToTable("Psychologist");

                    b.HasDiscriminator().HasValue("Psychologist");
                });

            modelBuilder.Entity("DomainModels.Models.EmployeeEntities.Scout", b =>
                {
                    b.HasBaseType("DomainModels.Models.EmployeeEntities.Employee");


                    b.ToTable("Scout");

                    b.HasDiscriminator().HasValue("Scout");
                });

            modelBuilder.Entity("DomainModels.Models.BuildingEntities.Building", b =>
                {
                    b.HasOne("DomainModels.Models.Club", "Club")
                        .WithMany("Buildings")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.Club", b =>
                {
                    b.HasOne("DomainModels.Models.User", "User")
                        .WithOne("Club")
                        .HasForeignKey("DomainModels.Models.Club", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.EmployeeEntities.Employee", b =>
                {
                    b.HasOne("DomainModels.Models.Club", "Club")
                        .WithMany("Employees")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.PlayerEntities.Player", b =>
                {
                    b.HasOne("DomainModels.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.PlayerEntities.PlayerStats", b =>
                {
                    b.HasOne("DomainModels.Models.PlayerEntities.Player", "Player")
                        .WithOne("Stats")
                        .HasForeignKey("DomainModels.Models.PlayerEntities.PlayerStats", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.PlayerEntities.PlayerTemporaryStats", b =>
                {
                    b.HasOne("DomainModels.Models.PlayerEntities.Player", "Player")
                        .WithOne("TemporaryStats")
                        .HasForeignKey("DomainModels.Models.PlayerEntities.PlayerTemporaryStats", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.SquadEntities.FormationPosition", b =>
                {
                    b.HasOne("DomainModels.Models.SquadEntities.Squad", "Squad")
                        .WithMany("FormationPositions")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.SquadEntities.Squad", b =>
                {
                    b.HasOne("DomainModels.Models.Club", "Club")
                        .WithMany("Squads")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.TournamentEntities.Match", b =>
                {
                    b.HasOne("DomainModels.Models.TournamentEntities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.TournamentEntities.MatchEvent", b =>
                {
                    b.HasOne("DomainModels.Models.TournamentEntities.Match", "Match")
                        .WithMany("MatchEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainModels.Models.TournamentEntities.TournamentClub", b =>
                {
                    b.HasOne("DomainModels.Models.Club", "Club")
                        .WithMany("TournamentClubs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DomainModels.Models.TournamentEntities.Tournament", "Tournament")
                        .WithMany("TournamentClubs")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
